# System Setup
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
port:         8000

# Site Details
title:        "The Nadine Project"
tagline:      "Open Source Coworking Platform"
description:  "Django web application to help manage membes in a coworking space."
authors:      "Jacob Sayles, Alice Wicks, Griffin Wesler"

# Custom vars
email:             "info@nadineproject.org"
github_url:        "https://github.com/nadineproject/nadine"
google-analytics:  "UA-29552936-1"
