# System Setup
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
port:         8000

# Site Details
title:        "The Nadine Project"
tagline:      "Open Source Member Managment Platform"
description:  "Django web application to help manage membes in a your community of members."
authors:      "Jacob Sayles, Alice Wicks, Griffin Wesler"

# Custom vars
email:            "info@nadineproject.org"
source_url:       "https://github.com/nadineproject/nadine"
docs_url:         "https://nadine.readthedocs.io/en/main/"
download_url:     "https://github.com/nadineproject/nadine/releases"
forum_url:        "https://github.com/nadineproject/nadine/discussions"
google-analytics: "UA-29552936-1"
